server:
  port : 8080

spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-34-200-94-86.compute-1.amazonaws.com:5432/d113h29a9om8ev
        username: xkeejluxismrfk
        password: 5e85ac2bda87b4545ba78c8fd8f62d98553dbe92f9ff0f2173e71adff5fe4667
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

    jpa: 
        hibernate:
            ddl-auto: create-drop
   
    